### ISSUE TITLE
Trying to add the switch to a sidedrawer

### ISSUE THREAD

**Issue by justinjk007** [divyanshub024/day_night_switch#1]
![Screenshot from 2019-09-29 13-25-33](https://user-images.githubusercontent.com/12916795/65836121-e548e700-e2bc-11e9-91c0-e93af54c3c78.png)

But the size of the widget is always out pf proportion, tried wrapping the switch in a container which made it non-responsive Any ideas how to make this switch the size of a regular switch ?

**Comment by divyanshub024** [comment]
Instead of putting it inside the container put it inside of scale.
```
Transform.scale(
  scale: 0.5,
  child: DayNightSwitch(
   ....
  ),
)
```

**Comment by justinjk007** [comment]
I wish this is applied by default, after all that's the normal use case. It worked btw.

**Comment by divyanshub024** [comment]
Will try to fix this in the next release.
